In [1]:
import pandas as pd
df = pd.read_excel('file/score.xlsx',index_col='지원번호')

In [2]:
df['학교'].value_counts()

학교
구로고     5
디지털고    3
Name: count, dtype: int64

In [3]:
# 그룹핑 groupby : size,mean,sum,min,max
# df.groupby('학교').get_group('구로고')
# df.groupby('학교').get_group('디지털고')
df['학교'].unique()
df.groupby('학교').size() 
df.groupby('학교').size()['디지털고']
df.groupby('학교').size()  # 학교기준으로 그룹핑을 해서 크기
df.groupby('학교')['키'].mean() # 학교기준으로 키 평균
df.groupby('학교')['국어'].mean()
df.groupby('학교')[['국어','영어','수학']].count()

      국어  영어  수학
학교
구로고    5   5   5
디지털고   3   3   3

In [4]:
df['학년'] = [3,3,2,1,1,3,2,2]

In [5]:
df

       이름    학교    키   국어   영어   수학  과학  사회        SW특기  학년
지원번호
1번    강나래   구로고  197   90   85  100  95  85      Python   3
2번    강태원   구로고  184   40   35   50  55  25        Java   3
3번    강호림   구로고  168   80   75   70  80  75  Javascript   2
4번    김수찬   구로고  187   40   60   70  75  80         NaN   1
5번    김재욱   구로고  188   15   20   10  35  10         NaN   1
6번    박동현  디지털고  202   80  100   95  85  80           C   3
7번    박혜정  디지털고  188   55   65   45  40  35      PYTHON   2
8번    승근열  디지털고  190  100   85   90  95  95          C#   2

In [6]:
# 그룹핑을 한후 개수 확인
df.groupby('학교').size()
df['학교'].value_counts()

학교
구로고     5
디지털고    3
Name: count, dtype: int64

In [7]:
df.groupby('학교')['학년'].value_counts().loc['구로고']
df.groupby('학교')['학년'].value_counts().loc['디지털고']
# normalize 백분율로 표시 : 원형 그래프
df.groupby('학교')['학년'].value_counts(normalize=True).loc['구로고']

학년
3    0.4
1    0.4
2    0.2
Name: proportion, dtype: float64

In [8]:
# df.groupby('학년')['키'].mean().sort_values()
df.groupby('학년')[['국어','영어']].sum().sort_values('국어') # 기준추가
df.groupby('학교')[['국어','영어']].mean().sort_values('영어')
df.groupby('학교')[['국어','영어']].count().sort_values('영어')

      국어  영어
학교
디지털고   3   3
구로고    5   5

In [11]:
df = pd.read_csv('file/drinks.csv')
df.groupby('continent').size().sort_values(ascending=False)

continent
AF    53
EU    45
AS    44
OC    16
SA    12
dtype: int64

In [13]:
df = pd.read_csv('file/drinks.csv')
# continent 대륙별 퍼센트를 출력하시오.
(df['continent'].value_counts(normalize=True)*100)

continent
AF    31.176471
EU    26.470588
AS    25.882353
OC     9.411765
SA     7.058824
Name: proportion, dtype: float64