In [2]:
# 데이터선택 - row

In [3]:
import pandas as pd
df = pd.read_excel('file/score.xlsx',index_col='지원번호')

In [4]:
#loc-이름검색,iloc-index주소로 검색
df.loc['1번']
df.iloc[0]
df.index # index 모두 출력
df.columns # columns 모두 출력

Index(['이름', '학교', '키', '국어', '영어', '수학', '과학', '사회', 'SW특기'], dtype='str')

In [6]:
# 컬럼 슬라이싱은 columns을 활용
# df['학교':'영어']  # col이름으로 슬라이싱 안됨.
# df[df.columns[1:5]] # columns 슬라이싱가능

# loc 형태 - row출력
df.loc['3번']         # 1개출력
df.loc[['1번','2번']] # 2개출력
df.loc['3번','국어']  # 1개row에서 국어컬럼만 출력
df.loc['1번':'4번']   # 1번~4번까지 출력
df.loc['1번':'4번','학교':'영어'] # index슬라이싱, column슬라이싱
df.loc['1번':'4번',['학교','영어']] # index슬라이싱, column2개는 리스트
df.loc[['1번','4번'],['학교','영어']] # index2개는리스트, column슬라이싱

       학교  영어
지원번호
1번    신림고  85
4번    신림고  60

In [ ]:
# loc 형태 - row출력
df.loc['1번':'4번']
df.loc['1번':'4번']
df.iloc[0]
df.iloc[0:4]     
df.iloc[0,2,4]         # 2개는 리스트
df.iloc[0:4]           
df.iloc[0:3,1:5]
df.iloc[[0,2],1:5]
df.iloc[[0,2],[1,3,5]]

       이름   학교    키  국어  영어   수학  과학  사회        SW특기
지원번호
1번    강나래  신림고  197  90  85  100  95  85      Python
2번    강태원  신림고  184  40  35   50  55  25        Java
3번    강호림  신림고  168  80  75   70  80  75  Javascript
4번    김수찬  신림고  187  40  60   70  75  80         NaN

In [10]:
df = pd.read_excel('file/연령별인구현황_2025.xlsx',skiprows=3,usecols='B:D,J:O',index_col='행정기관')
df.iloc[[0,2,5],[0,1,2,4,5]]

c:\python313\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

              총 인구수     연령구간인구수     50~59세     70~79세     80~89세
행정기관
전국       51,159,889  51,159,889  8,684,663  4,381,844  2,144,715
부산광역시     3,251,625   3,251,625    533,582    352,270    152,648
광주광역시     1,398,538   1,398,538    242,861    107,235     51,212